### ISSUE TITLE
Output truncated when installing plugins with plug.fish

### ISSUE THREAD

**Issue by marcransome** [fish-shop/install-plugin#2]
When installing plugins with the `plug.fish` plugin manager, action output appears to be truncated:

<img width="863" alt="Screenshot 2021-05-23 at 20 35 44" src="https://user-images.githubusercontent.com/679401/119274161-7db87b80-bc06-11eb-940d-cc0e8803e0d2.png">

The lack of detail can obscure the fact that the action was successful.

**To Reproduce**

Add the `install-plugin` action to a workflow job and specify the `plug.fish` plugin manager and a suitable `plugins` value:

```yaml
- name: Install Pond
  uses: fish-shop/install-plugin@main
  with:
    plugin-manager: plug.fish
    plugins: marcransome/pond
```

**Expected behavior**

The following output is expected, which includes both messages from the `plug.fish` plugin manager and the plugin being installed (differentiated by prefix):

```console
plug: installing marcransome/pond from https://github.com/marcransome/pond
plug: enabling marcransome/pond
pond: Setting pond editor to command: /usr/local/bin/vim
pond: Change editor with: set -U pond_editor <path>
```

**Additional context**

The truncated portions of the output are rendered in bold when testing `plug.fish` locally. This issue is likely related to terminal capabilities and the `TERM` environment variable.
