### ISSUE TITLE
Reuse install-plugin-manager  composite action code

### ISSUE THREAD

**Issue by marcransome** [fish-shop/install-plugin#4]
This action duplicates some code from the [fish-shop/install-plugin-manager](https://github.com/fish-shop/install-plugin-manager) action. Specifically, the code used to install the desired plugin manager. 🤔 

It would be preferable to include the [fish-shop/install-plugin-manager](https://github.com/fish-shop/install-plugin-manager) action in a conditional `uses` step to avoid such duplication of code (i.e. to only install the desired plugin manager if it is not already installed).

**Proposed solution**

The following prototype solution includes an upfront check to determine the presence of the specified plugin manager, coupled with an environment variable (`plugin_manager_installed`) and conditional `uses` step to install the plugin manager when necessary:

```yaml
runs:
  using: 'composite'
  steps:
    - name: Check for plugin manager
      run: |
        if type -q ${{ inputs.plugin-manager }}
            echo "plugin_manager_installed=true" >> $GITHUB_ENV
        else
            echo "plugin_manager_installed=false" >> $GITHUB_ENV
        end
      shell: fish {0}
    - name: Install plugin manager
      if: ${{ env.plugin_manager_installed == 'false' }}
      uses: fish-shop/install-plugin-manager@main
      with:
        plugin-manager: ${{ inputs.plugin-manager }}
      shell: fish {0}
    - name: Install plugins
      run: |
        ...
      shell: fish {0}
```

**Current state**

It is not currently possible to include a `uses` step in a composite action (i.e. nesting composite actions) as detailed in the thread [Next Steps for Fully Functioning Composite Actions](https://github.com/actions/runner/issues/646). Specifically (emphasis my own):

> We don't support setting **conditionals**, continue-on-error, timeout-minutes, **"uses"**, and secrets on individual steps within a composite action right now.

Until further progress is made towards adding support for conditionals and `uses` in composite actions this issue will be put **on hold**. ⏳
